apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivia-deployment-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivia-project-front
  template:
    metadata:
      labels:
        app: trivia-project-front
    spec:
      containers:
        - name: trivia-frontend
          image: katlosyeva/trivia:latest
          ports:
            - containerPort: 3000
        

---

apiVersion: v1
kind: Service
metadata:
  name: trivia-service-front
spec:
  selector:
    app: trivia-project-front
  ports:
    - name: front-listener
      protocol: TCP
      port: 3000
      targetPort: 3000  # Assuming React frontend runs on port 3000
      nodePort: 31515
  type: NodePort