apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivia-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivia-project-db
  template:
    metadata:
      labels:
        app: trivia-project-db
    spec:
      containers:
        - name: mysql-database
          image: katlosyeva/trivia-db:latest
          ports:
            - containerPort: 3306 
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: private

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: trivia-project-db
  ports:
    - name: sql-listener
      protocol: TCP
      port: 3306
      targetPort: 3306 
  type: LoadBalancer
       